### PR TITLE
Add options to set point characters

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves https://github.com/jstrace/chart/issues/8

### CODE REVIEW

**Comment by tj** [comment]
thanks! Added you to the repo as well since I'm not in node-land anymore

**Comment by lukechilds** [comment]
Sweet, accepted.

What land do you reside in now?

**Comment by tj** [comment]
Mostly Go these days for backend stuff

**Comment by lukechilds** [comment]
Nice, I have Go and Rust on my todo list to check out.

Would you mind adding me to this on npm too so I can publish a new version?

`npm owner add lukechilds ascii-chart`

**Comment by tj** [comment]
Added!

**Comment by lukechilds** [comment]
👌

**Pull request merged**
